name: Build

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: Go lint
        run: |
          go install golang.org/x/lint/golint@latest
          golint .

      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticccheck .

      - name: Build for Linux-amd64
        run: go build -o rewinged_linux_amd64 .
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Build for Windows-amd64
        run: go build -o rewinged_windows_amd64.exe .
        env:
          GOOS: windows
          GOARCH: amd64
